export const SET_TITLE = 'SET_TITLE'

export const SET_SOURCE_ADDRESS = 'SET_SOURCE_ADDRESS'
export const SET_DESTINATION_ADDRESS = 'SET_DESTINATION_ADDRESS'
export const SET_TRAVEL_ROUTES = 'SET_TRAVEL_ROUTES'

export const SET_UNIVERSITIES = 'SET_UNIVERSITIES'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'

export const HIDE_SIDE_MENU = 'HIDE_SIDE_MENU'
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU'
